version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - springboot2_data:/var/lib/mysql


volumes:
  springboot2_data: